apiVersion: apps/v1
kind: Deployment
metadata:
  name: quest-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quest
  template:
    metadata:
      labels:
        app: quest
    spec:
      containers:
        - name: quest-container
          image: gcr.io/northstar-449004/new-app:4.0
          ports:
            - containerPort: 443
          env:
            - name: SECRET_WORD
              value: "TwelveFactor"
          volumeMounts:
            - name: certs-volume
              mountPath: /certs
              readOnly: true
            - name: private-key-volume
              mountPath: /private
              readOnly: true
      volumes:
        - name: certs-volume
          secret:
            secretName: my-tls-secret
            items:
              - key: tls.crt
                path: tls.crt
        - name: private-key-volume
          secret:
            secretName: my-tls-secret
            items:
              - key: tls.key
                path: tls.key
---
apiVersion: v1
kind: Service
metadata:
  name: quest-service-tls
spec:
  selector:
    app: quest
  ports:
    - protocol: TCP
      port: 443  # TLS port
      targetPort: 443  # App's HTTP port (assuming your app handles TLS)
  type: LoadBalancer
